### ISSUE TITLE
npm install failing

### ISSUE THREAD

**Issue by Jursdotme** [kogakure/gulp-tutorial#7]
Fresh clone of this project gives me the following error on `npm install`. Afterwards multiple modules are missing. Any thoughts?

```shell
Rasmuss-iMac:jursdotme-jekyll rasmusjurs$ npm install
npm WARN engine imagemin@2.2.1: wanted: {"node":">=0.10.0","npm":">=2.1.5"} (current: {"node":"0.10.36","npm":"1.4.28"})
 
> fsevents@0.3.5 install /Users/rasmusjurs/Desktop/jursdotme-jekyll/node_modules/watchify/node_modules/chokidar/node_modules/fsevents
> node-gyp rebuild

  SOLINK_MODULE(target) Release/.node
  SOLINK_MODULE(target) Release/.node: Finished
  CXX(target) Release/obj.target/fse/fsevents.o
  SOLINK_MODULE(target) Release/fse.node
  SOLINK_MODULE(target) Release/fse.node: Finished
 
> gmsmith@0.4.5 preinstall /Users/rasmusjurs/Desktop/jursdotme-jekyll/node_modules/gulp.spritesmith/node_modules/spritesmith/node_modules/gmsmith
> gm -version || convert -version

sh: gm: command not found
sh: convert: command not found
npm WARN optional dep failed, continuing gmsmith@0.4.5
 
> phantomjssmith@0.5.4 preinstall /Users/rasmusjurs/Desktop/jursdotme-jekyll/node_modules/gulp.spritesmith/node_modules/spritesmith/node_modules/phantomjssmith
> phantomjs --version

sh: phantomjs: command not found
npm WARN optional dep failed, continuing phantomjssmith@0.5.4
npm WARN engine pngjs@0.4.0: wanted: {"node":"0.8.x"} (current: {"node":"0.10.36","npm":"1.4.28"})
 
> canvas@1.1.6 install /Users/rasmusjurs/Desktop/jursdotme-jekyll/node_modules/gulp.spritesmith/node_modules/spritesmith/node_modules/canvassmith/node_modules/canvas
> node-gyp rebuild

./util/has_cairo_freetype.sh: line 4: pkg-config: command not found
gyp: Call to './util/has_cairo_freetype.sh' returned exit status 0. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:343:16)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
gyp ERR! System Darwin 14.0.0
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/rasmusjurs/Desktop/jursdotme-jekyll/node_modules/gulp.spritesmith/node_modules/spritesmith/node_modules/canvassmith/node_modules/canvas
gyp ERR! node -v v0.10.36
gyp ERR! node-gyp -v v1.0.1
gyp ERR! not ok 
npm WARN optional dep failed, continuing canvassmith@0.2.4
|
> gifsicle@2.0.1 postinstall /Users/rasmusjurs/Desktop/jursdotme-jekyll/node_modules/gulp-imagemin/node_modules/imagemin/node_modules/imagemin-gifsicle/node_modules/gifsicle
> node lib/install.js

  ✔ gifsicle pre-build test passed successfully


> optipng-bin@2.0.4 postinstall /Users/rasmusjurs/Desktop/jursdotme-jekyll/node_modules/gulp-imagemin/node_modules/imagemin/node_modules/imagemin-optipng/node_modules/optipng-bin
> node lib/install.js

  ✔ optipng pre-build test passed successfully

> cwebp-bin@2.0.4 postinstall /Users/rasmusjurs/Desktop/jursdotme-jekyll/node_modules/gulp-webp/node_modules/cwebp-bin
> node install.js

  ✔ cwebp pre-build test passed successfully

> pngquant-bin@2.0.3 postinstall /Users/rasmusjurs/Desktop/jursdotme-jekyll/node_modules/gulp-imagemin/node_modules/imagemin/node_modules/imagemin-pngquant/node_modules/pngquant-bin
> node lib/install.js

  ✔ pngquant pre-build test passed successfully

> jpegtran-bin@2.0.2 postinstall /Users/rasmusjurs/Desktop/jursdotme-jekyll/node_modules/gulp-imagemin/node_modules/imagemin/node_modules/imagemin-jpegtran/node_modules/jpegtran-bin
> node lib/install.js

  ✔ jpegtran pre-build test passed successfully
npm ERR! EEXIST, open '/Users/rasmusjurs/.npm/d8f15c9f-adable-stream-1-0-33-package-tgz.lock'
File exists: /Users/rasmusjurs/.npm/d8f15c9f-adable-stream-1-0-33-package-tgz.lock
Move it away, and try again. 

npm ERR! System Darwin 14.0.0
npm ERR! command "node" "/usr/local/bin/npm" "install"
npm ERR! cwd /Users/rasmusjurs/Desktop/jursdotme-jekyll
npm ERR! node -v v0.10.36
npm ERR! npm -v 1.4.28
npm ERR! path /Users/rasmusjurs/.npm/d8f15c9f-adable-stream-1-0-33-package-tgz.lock
npm ERR! code EEXIST
npm ERR! errno 47
npm ERR! not ok code 0
```

**Comment by kogakure** [comment]
One error looks familiar to me, this is some known bug on OS X. Before compiling execute this task: `export PKG_CONFIG_PATH=/opt/X11/lib/pkgconfig`. This helped for me. Maybe there is another bug, looks like PhantomJS is missing?
